name: Deploy to cPanel via FTP

on:
  push:
    branches:
      - main   # Runs when you push to main branch
  workflow_dispatch: # Allows manual trigger

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: FTP Deploy to cPanel
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          local-dir: ./   # The folder to upload (your WordPress files)
          server-dir: /public_html/  # Path on your cPanel server
