name: Deploy to cPanel via FTP

on:
  push:
    branches: [ "main" ]   # Deploy when pushing to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          server-dir: /public_html/   # 👈 change if deploying only theme/plugin
          local-dir: ./               # deploys everything in repo
          exclude: |
            **/.git*
            **/.github/*
            **/node_modules/*
            **/tests/*
