name: Deploy to cPanel via FTP

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: FTP Deploy to cPanel
        uses: SamKirkland/FTP-Deploy-Action@v4
        with:
          server: ftp.example.com
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./ # your local folder
          server-dir: /public_html/
